### ISSUE TITLE
version 6.1.x doesn't seem to compatible with other version

### ISSUE THREAD

**Issue by bhsiung** [linkedin/eyeglass#228]
**Package**
This issue is related to the following monorepo package(s):
- [ ] eyeglass 
- [ ] broccoli-eyeglass
- [x] ember-cli-eyeglass

**Description**
When more than one version is installed (in our case, `v1.4.2` + `v5.1.2` + `v6.*`) which cause either of these issues.
```
stack: TypeError: Cannot read property 'sessionCache' of undefined
    at Class.setupConfig (/export/content/data/mp-trunkdev-mpdep/i001/workspace/ember-ts-project-create_43702497a2ddee79398cbd47b9c09ddd727249f1/node_modules/@linkedin/helpcenter-in-product-ember/node_modules/ember-cli-eyeglass/lib/index.js:197:58)
```

```
Unhandled rejection TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at BroccoliSymbolicLinker.ln_s (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/ember-cli-eyeglass/lib/broccoli-ln-s.js:65:21)
    at Class.linkAsset (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/ember-cli-eyeglass/lib/index.js:192:23)
    at /Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/ember-cli-eyeglass/lib/index.js:223:32
    at Assets.install (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/eyeglass/lib/assets/Assets.js:206:13)
    at /Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/broccoli-eyeglass/lib/index.js:126:13
    at Assets.install (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/eyeglass/lib/assets/Assets.js:206:13)
    at /Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/eyeglass/lib/assets/Assets.js:122:28
    at Assets.resolve (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/eyeglass/lib/assets/Assets.js:148:9)
    at /Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/broccoli-eyeglass/lib/index.js:122:17
    at tryCatcher (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/chained-emitter/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/chained-emitter/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/chained-emitter/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/chained-emitter/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/chained-emitter/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/nballamb/li-work/remote/ember-cli-ts-inmail_trunk/node_modules/chained-emitter/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

**Expected behavior**
Expecting ember-cli-eyeglass can be operate when multiple versions are installed

**Current workaround**
Set yarn resolution to force all `ember-cli-eyeglass` dependencies to `6.0.1`

**Comment by chriseppstein** [comment]
We require ember-cli 3.5 or greater. I've added an entry for `peerDependencies`.
